### ISSUE TITLE
There are some issues in Header.php.

### ISSUE THREAD

**Issue by Pasindulak** [randika-chathuranga/Blood-donation-web-project#11]
Some images are missing and the alignments of the navigation bar should be fixed. 
![header](https://user-images.githubusercontent.com/56922990/124307100-f35c2380-db84-11eb-8852-89e875be6e9c.PNG)

**Comment by Pasindulak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[HFX-002] There are some issues in Header.php to be fixed.](https://trello.com/c/LeN6tYTx/23-hfx-002-there-are-some-issues-in-headerphp-to-be-fixed)

**Comment by ThiwankaShan** [comment]
fixed in hfx-003
